'use client';
import { lazy, Suspense, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { Map as MapboxMap } from 'mapbox-gl';
import { useTracks } from './use-tracks';
import { DEFAULT_APPEARANCE, DEFAULT_FILTERS, HEAT_COLORS, TIME_COLORS, type Appearance } from './track-types';

const FootprintMap = lazy(() => import('./FootprintMap').then(module => ({ default: module.FootprintMap })));
const day = (time: number) => new Date(time * 1000).toISOString().slice(0, 10);
const format = (value?: number) => value === undefined ? '—' : value.toLocaleString('en-US');
const COLOR_PRESETS = [{ name:'海盐',color:'#55d6ff' },{ name:'虹彩',color:'#9b7bff' },{ name:'樱桃',color:'#ff4f87' },{ name:'橘光',color:'#ff653f' },{ name:'青柠',color:'#b8f34b' }];
const MAP_STYLES = [{ value:'dark',label:'深色',icon:'◐' },{ value:'light',label:'浅色',icon:'○' },{ value:'satellite',label:'卫星',icon:'◉' },{ value:'outdoors',label:'地形',icon:'⌁' }] as const;
const STORAGE = 'trace-appearance-v6';
type DockTab = 'style' | 'time' | 'stats';
type PlaceStats = { sourcePlaces:number; countries:{name:string;visits:number}[]; regions:{name:string;visits:number}[]; cities:{name:string;visits:number}[] };

function loadAppearance(): Appearance {
  try {
    const value = JSON.parse(localStorage.getItem(STORAGE) || '{}'), next = { ...DEFAULT_APPEARANCE };
    for (const key of ['pointColor','flightColor'] as const) if (/^#[0-9a-f]{6}$/i.test(value[key])) next[key] = value[key];
    const choices = { mode:['points','heat'], colorMode:['time','solid'], heatPalette:['aurora','ember','ocean'], flights:['show','hide','only'], mapStyle:['dark','light','satellite','outdoors'] };
    for (const key of Object.keys(choices) as (keyof typeof choices)[]) if (choices[key].includes(value[key])) Object.assign(next,{[key]:value[key]});
    for (const [key,min,max] of [['radius',.6,3],['opacity',.2,1],['heatRadius',1,120],['heatIntensity',.2,4]] as const) if (Number.isFinite(value[key])) next[key] = Math.max(min,Math.min(max,value[key]));
    return next;
  } catch { return DEFAULT_APPEARANCE; }
}

export default function Home() {
  const [filters,setFilters] = useState(DEFAULT_FILTERS), [appearance,setAppearance] = useState(DEFAULT_APPEARANCE);
  const [preferencesReady,setPreferencesReady] = useState(false), [activeTab,setActiveTab] = useState<DockTab | null>(null);
  const [dateMode,setDateMode] = useState<'range'|'day'>('range'), [calendarMonth,setCalendarMonth] = useState('');
  const [placeStats,setPlaceStats] = useState<PlaceStats | null>(null), [map,setMap] = useState<MapboxMap | null>(null);
  const [mapError,setMapError] = useState(''), [renderedRevision,setRenderedRevision] = useState(-1);
  const { meta,selection,pending,error } = useTracks(filters);
  const ready = useCallback((instance:MapboxMap) => setMap(instance),[]);
  const dataReady = useCallback((revision:number) => { setRenderedRevision(revision); setMapError(''); },[]);
  const reportError = useCallback((message:string) => setMapError(message),[]);
  useEffect(() => { setAppearance(loadAppearance()); setPreferencesReady(true); fetch(new URL('place-stats.json',document.baseURI)).then(value => value.json() as Promise<PlaceStats>).then(setPlaceStats).catch(() => {}); },[]);
  useEffect(() => { if (!calendarMonth && meta) setCalendarMonth(day(meta.maxTime).slice(0,7)); },[calendarMonth,meta]);
  useEffect(() => { setRenderedRevision(-1); },[appearance.mapStyle]);
  useEffect(() => { const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setActiveTab(null);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close); },[]);
  useEffect(() => { if(!preferencesReady)return;const timer=setTimeout(()=>{try{localStorage.setItem(STORAGE,JSON.stringify(appearance));}catch{}},250);return()=>clearTimeout(timer); },[appearance,preferencesReady]);

  const update = <K extends keyof Appearance>(key:K,value:Appearance[K]) => setAppearance(previous => ({...previous,[key]:value}));
  const busy = pending || !!selection && selection.revision !== renderedRevision;
  const visibleCount = selection ? appearance.flights === 'hide' ? selection.groundCount : appearance.flights === 'only' ? selection.flightCount : selection.count : undefined;
  const visibleDays = selection ? appearance.flights === 'hide' ? selection.groundDays : appearance.flights === 'only' ? selection.flightDays : selection.days : undefined;
  const minDate = meta ? day(meta.minTime) : '', maxDate = meta ? day(meta.maxTime) : '';
  const dateLabel = filters.start || filters.end ? `${filters.start || minDate} — ${filters.end || filters.start || maxDate}` : '全部日期';
  const setDate = (value:string) => setFilters(previous => ({...previous,start:value,end:value}));
  const preset = (days:number) => { if(!meta)return;setDateMode('range');setFilters(previous=>({...previous,start:day(Date.parse(maxDate+'T00:00:00Z')/1000-(days-1)*86400),end:maxDate})); };
  const fit = () => { const bounds=appearance.flights==='hide'?selection?.groundBounds:appearance.flights==='only'?selection?.flightBounds:selection?.bounds;if(map&&bounds)map.fitBounds([[bounds[0],bounds[1]],[bounds[2],bounds[3]]],{padding:{top:70,bottom:activeTab?360:100,left:50,right:50},maxZoom:16,duration:700}); };
  const heatGradient = `linear-gradient(90deg,${HEAT_COLORS[appearance.heatPalette].join(',')})`;
  const pointGradient = appearance.colorMode==='time'?`linear-gradient(90deg,${TIME_COLORS.join(',')})`:appearance.pointColor;

  return <main className="app-shell">
    <header className="topbar"><div className="brand"><span className="brand-mark" aria-hidden="true">⌁</span><div><strong>TRACE <span>/ 足迹</span></strong><small>PERSONAL MOVEMENT ARCHIVE</small></div></div><span className="period">{meta?`${minDate.slice(0,4)} — ${maxDate.slice(0,4)}`:'加载数据中'}</span><span className="top-count"><i/>{format(visibleCount)} 个点</span></header>
    <section className="map-stage">
      <Suspense fallback={<div className="loader">正在启动地图…</div>}><FootprintMap selection={selection} appearance={appearance} onReady={ready} onDataReady={dataReady} onError={reportError}/></Suspense>
      <div className="map-caption"><span className="eyebrow">YOUR WORLD, IN POINTS</span><h1>足迹档案</h1><p>{dateLabel}</p></div>
      <div className="map-status" role="status"><i className={busy?'status-light busy':'status-light'}/>{busy?selection?'正在更新图层 · 地图仍可操作':'正在读取完整足迹…':`${format(visibleCount)} 个筛选点位`}</div>
      {(error||mapError)&&<div className="error-banner" role="alert">{error||mapError}<button onClick={()=>window.location.reload()}>重新加载</button></div>}
      {!busy&&selection&&visibleCount===0&&<div className="empty-state"><strong>这个条件下没有足迹</strong><p>试试其他日期，或显示全部航迹。</p><button onClick={()=>{setFilters(DEFAULT_FILTERS);update('flights','show');}}>清除筛选</button></div>}
      <div className="map-tools" aria-label="地图操作"><button aria-label="放大地图" onClick={()=>map?.zoomIn()}>＋</button><button aria-label="缩小地图" onClick={()=>map?.zoomOut()}>−</button><button aria-label="回到波士顿" onClick={()=>map?.flyTo({center:[-71.08,42.36],zoom:10})}>◎</button><button aria-label="定位筛选范围" disabled={!selection?.count} onClick={fit}>⤢</button></div>
      <div className="map-legend">{appearance.mode==='heat'?<><span>记录密度</span><i className="gradient-bar" style={{background:heatGradient}}/><span>低 → 高</span></>:<><i className="gradient-bar" style={{background:pointGradient}}/><span>{appearance.colorMode==='time'?'较早 → 最近':'足迹点'}</span>{appearance.flights!=='hide'&&<><i className="legend-dot" style={{background:appearance.flightColor}}/><span>疑似航迹</span></>}</>}</div>
      {activeTab&&<section id="controls" className={`glass-panel panel-${activeTab}`} aria-label="足迹控制面板"><header className="glass-heading"><div><span>{activeTab==='style'?'APPEARANCE':activeTab==='time'?'TIME WINDOW · UTC':'JOURNEY INSIGHTS'}</span><h2>{activeTab==='style'?'样式调整':activeTab==='time'?'时间选择':'统计与航迹'}</h2></div><button aria-label="关闭面板" onClick={()=>setActiveTab(null)}>×</button></header>{activeTab==='style'&&<StylePanel appearance={appearance} update={update} setAppearance={setAppearance}/>} {activeTab==='time'&&<TimePanel meta={meta} filters={filters} setFilters={setFilters} dateMode={dateMode} setDateMode={setDateMode} month={calendarMonth} setMonth={setCalendarMonth} minDate={minDate} maxDate={maxDate} dateLabel={dateLabel} setDate={setDate} preset={preset}/>} {activeTab==='stats'&&<StatsPanel stats={placeStats} selection={selection} appearance={appearance} update={update} filters={filters} setFilters={setFilters}/>}</section>}
      <nav className="control-dock" aria-label="主要工具">{([['style','◑','样式'],['time','◷','时间'],['stats','⌁','统计']] as const).map(([value,icon,label])=><button key={value} aria-pressed={activeTab===value} aria-controls="controls" onClick={()=>setActiveTab(previous=>previous===value?null:value)}><i>{icon}</i><span>{label}</span>{value==='time'&&filters.start&&<b/>}</button>)}<span className="dock-divider"/><button onClick={fit} disabled={!selection?.count}><i>⤢</i><span>定位</span></button></nav>
    </section>
    <footer><span>LOCAL ARCHIVE <i/> {meta?`${(meta.compressedByteLength/1024/1024).toFixed(1)} MB 下载`:'—'}</span><span>{format(meta?.count)} ORIGINAL POINTS · UTC</span></footer>
  </main>;
}

function StylePanel({appearance,update,setAppearance}:{appearance:Appearance;update:<K extends keyof Appearance>(key:K,value:Appearance[K])=>void;setAppearance:React.Dispatch<React.SetStateAction<Appearance>>}) {
  const color=appearance.colorMode==='solid'?appearance.pointColor:TIME_COLORS[2];
  return <div className="style-layout"><div className="style-options"><div className="inline-choice"><span>显示</span><div><button aria-pressed={appearance.mode==='points'} onClick={()=>update('mode','points')}>点位</button><button aria-pressed={appearance.mode==='heat'} onClick={()=>update('mode','heat')}>热力图</button></div></div>{appearance.mode==='points'?<><div className="inline-choice"><span>颜色</span><div><button aria-pressed={appearance.colorMode==='time'} onClick={()=>update('colorMode','time')}>随时间</button><button aria-pressed={appearance.colorMode==='solid'} onClick={()=>update('colorMode','solid')}>单色</button></div></div><div className="color-row">{COLOR_PRESETS.map(item=><button key={item.name} title={item.name} aria-label={item.name} aria-pressed={appearance.colorMode==='solid'&&appearance.pointColor===item.color} style={{'--swatch':item.color} as React.CSSProperties} onClick={()=>setAppearance(previous=>({...previous,pointColor:item.color,colorMode:'solid'}))}><i/></button>)}<label className="custom-color"><input type="color" aria-label="自定义足迹颜色" value={appearance.pointColor} onChange={event=>setAppearance(previous=>({...previous,pointColor:event.target.value,colorMode:'solid'}))}/><span>＋</span></label></div></>:<><span className="option-label">热力色谱</span><div className="heat-palettes">{(['aurora','ember','ocean'] as const).map((name,index)=><button key={name} aria-pressed={appearance.heatPalette===name} onClick={()=>update('heatPalette',name)}><i style={{background:`linear-gradient(90deg,${HEAT_COLORS[name].join(',')})`}}/><span>{['极光','熔金','潮汐'][index]}</span></button>)}</div></>}<button className="reset-button" onClick={()=>setAppearance(DEFAULT_APPEARANCE)}>恢复默认</button></div><div className="dial-pair">{appearance.mode==='points'?<><DialControl label="尺寸" value={appearance.radius} min={.6} max={3} step={.1} unit="px" color={color} onChange={value=>update('radius',value)}/><DialControl label="透明度" value={appearance.opacity} min={.2} max={1} step={.05} unit="%" color={color} onChange={value=>update('opacity',value)}/></>:<><DialControl label="扩散" value={appearance.heatRadius} min={1} max={120} step={1} unit="px" color={HEAT_COLORS[appearance.heatPalette][2]} onChange={value=>update('heatRadius',value)}/><DialControl label="强度" value={appearance.heatIntensity} min={.2} max={4} step={.1} unit="×" color={HEAT_COLORS[appearance.heatPalette][3]} onChange={value=>update('heatIntensity',value)}/></>}</div><div className="map-style-picker"><span className="option-label">地图样式</span>{MAP_STYLES.map(item=><button key={item.value} aria-pressed={appearance.mapStyle===item.value} onClick={()=>update('mapStyle',item.value)}><i>{item.icon}</i><span>{item.label}</span></button>)}</div></div>;
}

function TimePanel({meta,filters,setFilters,dateMode,setDateMode,month,setMonth,minDate,maxDate,dateLabel,setDate,preset}:{meta:ReturnType<typeof useTracks>['meta'];filters:typeof DEFAULT_FILTERS;setFilters:React.Dispatch<React.SetStateAction<typeof DEFAULT_FILTERS>>;dateMode:'range'|'day';setDateMode:(value:'range'|'day')=>void;month:string;setMonth:(value:string)=>void;minDate:string;maxDate:string;dateLabel:string;setDate:(value:string)=>void;preset:(days:number)=>void}) {
  const recorded=useMemo(()=>new Set(meta?.days.map(value=>value.date)||[]),[meta]);
  const cells=useMemo(()=>{if(!month)return[];const first=new Date(`${month}-01T00:00:00Z`),start=new Date(first);start.setUTCDate(1-first.getUTCDay());return Array.from({length:42},(_,index)=>{const date=new Date(start);date.setUTCDate(start.getUTCDate()+index);const iso=date.toISOString().slice(0,10);return{iso,label:date.getUTCDate(),inside:iso.slice(0,7)===month};});},[month]);
  const moveMonth=(offset:number)=>{const date=new Date(`${month}-01T00:00:00Z`);date.setUTCMonth(date.getUTCMonth()+offset);setMonth(date.toISOString().slice(0,7));};
  const select=(iso:string)=>{if(dateMode==='day'){setDate(iso);return;}if(!filters.start||filters.end)setFilters(previous=>({...previous,start:iso,end:''}));else if(iso<filters.start)setFilters(previous=>({...previous,start:iso,end:filters.start}));else setFilters(previous=>({...previous,end:iso}));};
  const monthLabel=month?new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long',timeZone:'UTC'}).format(new Date(`${month}-01T00:00:00Z`)):'';
  return <div className="time-layout"><div className="calendar"><div className="calendar-head"><button aria-label="上个月" disabled={!!minDate&&month<=minDate.slice(0,7)} onClick={()=>moveMonth(-1)}>‹</button><strong>{monthLabel}</strong><button aria-label="下个月" disabled={!!maxDate&&month>=maxDate.slice(0,7)} onClick={()=>moveMonth(1)}>›</button></div><div className="weekday">{['日','一','二','三','四','五','六'].map(value=><span key={value}>{value}</span>)}</div><div className="calendar-grid">{cells.map(cell=>{const selected=dateMode==='day'?filters.start===cell.iso:cell.iso===filters.start||cell.iso===filters.end,inRange=!!filters.start&&!!filters.end&&cell.iso>filters.start&&cell.iso<filters.end;return<button key={cell.iso} disabled={!cell.inside||cell.iso<minDate||cell.iso>maxDate} className={`${selected?'selected ':''}${inRange?'in-range ':''}${recorded.has(cell.iso)?'recorded':''}`} onClick={()=>select(cell.iso)}>{cell.label}</button>;})}</div></div><div className="time-side"><div className="inline-choice"><span>选择方式</span><div><button aria-pressed={dateMode==='day'} onClick={()=>setDateMode('day')}>某一天</button><button aria-pressed={dateMode==='range'} onClick={()=>setDateMode('range')}>时间段</button></div></div><div className="date-fields">{dateMode==='day'?<label><span>日期</span><input type="date" min={minDate} max={maxDate} value={filters.start} onChange={event=>setDate(event.target.value)}/></label>:<><label><span>开始</span><input type="date" min={minDate} max={maxDate} value={filters.start} onChange={event=>setFilters(previous=>({...previous,start:event.target.value}))}/></label><label><span>结束</span><input type="date" min={minDate} max={maxDate} value={filters.end} onChange={event=>setFilters(previous=>({...previous,end:event.target.value}))}/></label></>}</div><span className="option-label">快捷选择</span><div className="quick-dates"><button onClick={()=>preset(7)}>过去一周</button><button onClick={()=>preset(30)}>过去一月</button><button onClick={()=>preset(365)}>过去一年</button><button onClick={()=>setFilters(previous=>({...previous,start:'',end:''}))}>全部</button></div><div className="current-range"><span>当前范围</span><strong>{dateLabel}</strong><small>{format(meta?.days.length)} 个有记录的日期</small></div></div></div>;
}

function StatsPanel({stats,selection,appearance,update,filters,setFilters}:{stats:PlaceStats|null;selection:ReturnType<typeof useTracks>['selection'];appearance:Appearance;update:<K extends keyof Appearance>(key:K,value:Appearance[K])=>void;filters:typeof DEFAULT_FILTERS;setFilters:React.Dispatch<React.SetStateAction<typeof DEFAULT_FILTERS>>}) {
  return <div className="stats-layout"><div><div className="metric-row"><Metric label="国家" value={stats?.countries.length}/><Metric label="城市" value={stats?.cities.length}/><Metric label="地区" value={stats?.regions.length}/></div><div className="place-columns"><PlaceList title="常去城市" values={stats?.cities}/><PlaceList title="到访国家" values={stats?.countries}/></div><p className="stats-note">根据 {format(stats?.sourcePlaces)} 个已保存地点汇总；具体地址不会显示在这里。</p></div><div className="flight-card"><div className="flight-title"><span><i>✈</i> 航迹</span><strong>{format(selection?.flightCount)} <small>点</small></strong></div><div className="flight-visibility">{([['show','显示'],['hide','隐藏'],['only','仅航迹']] as const).map(([value,label])=><button key={value} aria-pressed={appearance.flights===value} onClick={()=>update('flights',value)}>{label}</button>)}</div><ThresholdControl label="海拔下限" value={filters.altitude} unit="m" step={100} min={0} max={15000} presets={[1500,2000,3000]} onChange={altitude=>setFilters(previous=>({...previous,altitude}))}/><label className="switch-row"><span><strong>速度辅助</strong><small>排除高海拔地面点</small></span><input type="checkbox" checked={filters.speedAssist} onChange={event=>setFilters(previous=>({...previous,speedAssist:event.target.checked}))}/><i/></label>{filters.speedAssist&&<ThresholdControl label="速度下限" value={filters.speed} unit="m/s" step={5} min={0} max={350} presets={[30,55,80]} onChange={speed=>setFilters(previous=>({...previous,speed}))}/>}<label className="flight-color">航迹颜色<input type="color" value={appearance.flightColor} onChange={event=>update('flightColor',event.target.value)}/></label></div></div>;
}

function Metric({label,value}:{label:string;value?:number}) { return <div className="metric"><strong>{format(value)}</strong><span>{label}</span></div>; }
function PlaceList({title,values}:{title:string;values?:{name:string;visits:number}[]}) { return <div className="place-list"><span>{title}</span>{values?.slice(0,5).map((item,index)=><div key={item.name}><b>{String(index+1).padStart(2,'0')}</b><strong>{item.name}</strong><small>{format(item.visits)}</small></div>)||<em>正在整理…</em>}</div>; }

function DialControl({label,value,min,max,step,unit,color,onChange}:{label:string;value:number;min:number;max:number;step:number;unit:string;color:string;onChange:(value:number)=>void}) {
  const drag=useRef<{y:number;value:number}|null>(null),set=(next:number)=>onChange(Math.round(Math.max(min,Math.min(max,next))*100)/100),normalized=(value-min)/(max-min),display=unit==='%'?Math.round(value*100):Number.isInteger(step)?Math.round(value):value.toFixed(1);
  return <div className="dial-control"><span className="dial-label">{label}</span><div className="dial-wrap"><div className="dial" role="slider" tabIndex={0} aria-label={label} aria-valuemin={unit==='%'?min*100:min} aria-valuemax={unit==='%'?max*100:max} aria-valuenow={Number(display)} onKeyDown={event=>{if(['ArrowLeft','ArrowDown'].includes(event.key)){event.preventDefault();set(value-step);}if(['ArrowRight','ArrowUp'].includes(event.key)){event.preventDefault();set(value+step);}}} onWheel={event=>{event.preventDefault();set(value+(event.deltaY<0?step:-step));}} onPointerDown={event=>{drag.current={y:event.clientY,value};event.currentTarget.setPointerCapture(event.pointerId);}} onPointerMove={event=>{if(drag.current){const sensitivity=(max-min)/180;set(drag.current.value+(drag.current.y-event.clientY)*sensitivity);}}} onPointerUp={event=>{drag.current=null;event.currentTarget.releasePointerCapture(event.pointerId);}} style={{'--dial-color':color,'--dial-fill':`${normalized*270}deg`,'--dial-angle':`${135+normalized*270}deg`} as React.CSSProperties}><i className="dial-indicator"/><span className="dial-value"><input aria-label={`${label}数值`} type="number" min={unit==='%'?min*100:min} max={unit==='%'?max*100:max} step={unit==='%'?step*100:step} value={display} onChange={event=>set(unit==='%'?+event.target.value/100:+event.target.value)}/><em>{unit}</em></span></div><button aria-label={`减小${label}`} onClick={()=>set(value-step)}>−</button><button aria-label={`增大${label}`} onClick={()=>set(value+step)}>＋</button></div><small>上下拖动 · 滚轮 · 方向键</small></div>;
}

function ThresholdControl({label,value,unit,presets,onChange}:{label:string;value:number;unit:string;step:number;min:number;max:number;presets:number[];onChange:(value:number)=>void}) { return <div className="threshold"><div className="threshold-head"><span>{label}</span><output>{value.toLocaleString()} {unit}</output></div><div className="threshold-presets">{presets.map(item=><button key={item} aria-pressed={value===item} onClick={()=>onChange(item)}>{item.toLocaleString()}</button>)}</div></div>; }
